name: Laravel Pint Code Style Tests
on:
  pull_request:
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: "laravel-pint"
        uses: aglipanci/laravel-pint-action@2.3.0
        with:
          preset: laravel
          verboseMode: true
          testMode: true
          pintVersion: 1.13.1
          onlyDirty: true
